
services:
  cpp-dev:
    build: .
    image: cpp-course:latest
    platform: linux/amd64
    volumes:
      - .:/home/student/workspace
    working_dir: /home/student/workspace
    stdin_open: true
    tty: true
    environment:
      - TERM=xterm-256color

